on:
  push:
    branches: main

jobs:
  states:
    strategy:
      matrix:
        state: [AL, AK]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      
      - name: Install R packages
        uses: r-lib/actions/setup-renv@v2
        env:
          RENV_CONFIG_PAK_ENABLED: true
      
      - name: do something
        run: Rscript script.R
        env:
          STATE: ${{ matrix.state }}